# 1. Basic App Info
spring.application.name=QuantityMeasurementApp
server.port=8080

# 2. H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=Arif@123
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# MySQL Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quantity_measurement
spring.datasource.username=root
spring.datasource.password=Arif@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 3. JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# 4. Logging & Security (Stops the confusion)
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
# This line stops the "Generated Security Password" from cluttering your console
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# 5. Actuator & Swagger
management.endpoints.web.exposure.include=health,metrics
springdoc.swagger-ui.enabled=true